### ISSUE TITLE
implement OAUTH with github

### ISSUE THREAD

**Issue by coded1guy** [GitHub-Campus-Experts-Unilag/DevZenBackend#2]
**Read the README.md file before you begin**

- setup the signup and login functionality in the /auth/services folder
- create the routes in the /auth/routes folder
- add the swagger documentation in the /auth/routes folder

**Comment by Alfred-Emmanuel** [comment]
Hi @coded1guy , can i be assigned to this issue?

**Comment by coded1guy** [comment]
@Alfred-Emmanuel still up for this?

**Comment by Alfred-Emmanuel** [comment]
Definitely @coded1guy

**Comment by Alfred-Emmanuel** [comment]
![Screenshot (121)](https://github.com/user-attachments/assets/6bec5708-ba1d-4e37-aada-edc56fd1c9d8)

There is currently an issue which came up as soon i cloned started the container, i have left a message on the social media group and i was told it would be fixed, i just thought to also let you know in order to know the reasons for any delay

**Comment by coded1guy** [comment]
Please bear with us, this issue has been fixed, but it uncovered another issue which is been rectified. I'll personally let you know once it has been resolved. Thank you for your patience.

**Comment by Alfred-Emmanuel** [comment]
Alright, thank you

**Comment by coded1guy** [comment]
Hey man, forgot to let you know to check, it should have been fixed now, so sorry for the late notification

**Comment by Alfred-Emmanuel** [comment]
No worries, thanks for the update!
